[package]
name = "nostr-social-graph-pubsub"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
nostr-pubsub.workspace = true
nostr-social-graph = { version = "0.1.0", path = "../nostr-social-graph" }
thiserror.workspace = true

[dev-dependencies]
nostr.workspace = true
nostr-social-graph-hashtree = { version = "0.1.0", path = "../nostr-social-graph-hashtree" }
tempfile.workspace = true
tokio.workspace = true
